#!/bin/sh

test -x "$PATH_QUOTA" || exit 1
test -x "$PATH_REPQUOTA" || exit 1

if test $# = 0; then
	set `echo [0-9][0-9].sh | sed -e 's/\.sh//g'`
fi

passes=0
total=$#
for t in $*; do
	printf "%s..........................................."  $t
	./$t.sh $quota $repquota >$t.out 2>&1
	rc=$?
	if test $rc != 0; then
		echo "failed rc=$rc, see $t.out"
	else
		diff $t.exp $t.out >$t.diff
		if test $? != 0; then
			echo "unexpected output, see $t.diff"
		else
			echo "success"
			passes=`expr $passes + 1`
		fi
	fi
done
echo $passes of $total tests passed 
exit `expr $total - $passes`
